-- 1. CREATE THE 'answers' TABLE (with updated_at column)
CREATE TABLE public.answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    question_id text NOT NULL,
    answer_value text,
    timestamp bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- 2. CREATE A TRIGGER to automatically update the 'updated_at' timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_answers_updated_at
BEFORE UPDATE ON public.answers
FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();


-- 3. ADD THE UNIQUE CONSTRAINT
ALTER TABLE public.answers
ADD CONSTRAINT answers_username_question_id_key UNIQUE (username, question_id);

-- 4. ENABLE RLS AND ADD POLICIES
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON public.answers FOR SELECT USING (true);

CREATE POLICY "Enable insert/update/delete for all users"
ON public.answers FOR ALL USING (true) WITH CHECK (true);